/** Build browser-compatible bundle and one-file offline demo. No dependencies. */
import { readFile, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = path => readFile(resolve(root, path), 'utf8');
const [machineSource, appSource, css, template] = await Promise.all([
  read('src/bubble-machine.js'), read('web/app.js'),
  read('web/styles.css'), read('web/index.html')
]);
const model = machineSource.replace(/^export class BubbleMachine/m, 'class BubbleMachine');
assert.notEqual(model, machineSource, 'BubbleMachine export not found');
const app = appSource.replace(/^import \{ BubbleMachine \} from ['"]\.\.\/src\/bubble-machine\.js['"];?\s*/m,'');
assert.notEqual(app, appSource, 'BubbleMachine import not found');
const bundle = `/* Generated by npm run build. Edit src/bubble-machine.js or web/app.js, not this file. */\n(() => {\nconst boot = () => {\n'use strict';\n${model}\n${app}\n};\nif (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot, { once: true });\nelse boot();\n})();\n`;
const onefile = template.replace(/<link rel="stylesheet" href="\.\/styles\.css">/, `<style>\n${css}\n</style>`)
  .replace(/<script defer src="\.\/app\.bundle\.js"><\/script>/, `<script>\n${bundle.replace(/<\/script/gi, '<\\/script')}\n</script>`)
  .replace('href="../src/sorts.js"', 'href="https://github.com/DearJIAN/classic-sorting-lab/blob/main/src/sorts.js"');
const outputs = [['web/app.bundle.js',bundle],['web/standalone.html',onefile]];
for(const [path, contents] of outputs){
 if(process.argv.includes('--check')){
   assert.equal(await read(path), contents, `${path} is stale; run npm run build`);
   console.log(`OK: ${path} matches its source`);
 }else {
   await writeFile(resolve(root,path),contents);
   console.log(`Built ${path} (${Buffer.byteLength(contents)} bytes)`);
 }
}
