/** Build a zero-dependency browser bundle and offline one-file HTML. */
import {readFile,writeFile} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>readFile(resolve(root,p),'utf8');
const [engine,app,css,html]=await Promise.all([read('src/trace-engine.js'),read('web/app.js'),read('web/styles.css'),read('web/index.html')]);
const model=engine.replace(/^export /gm,'');
assert.notEqual(model,engine,'Engine export not found');
const controller=app.replace(/^import \{ catalog, generateTrace, createExperimentReport, experimentReportToCsv \} from ['"]\.\.\/src\/trace-engine\.js['"];?\s*/m,'');
assert.notEqual(controller,app,'Engine import not found');
const bundle="/* Generated by npm run build. Edit source files, not this bundle. */\n(()=>{\nconst boot=()=>{\n'use strict';\n"+model+"\n"+controller+"\n};\nif(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();\n})();\n";
const onefile=html.replace('<link rel="stylesheet" href="./styles.css">','<style>\n'+css+'\n</style>').replace('<script defer src="./app.bundle.js"></script>','<script>\n'+bundle.replace(/<\/script/gi,'<\\/script')+'\n</script>');
assert.notEqual(onefile,html,'Offline HTML was not transformed');
for(const [path,content] of [['web/app.bundle.js',bundle],['web/standalone.html',onefile]]){
 if(process.argv.includes('--check')){assert.equal(await read(path),content,path+' is stale; run npm run build');console.log('PASS '+path+' matches source')}
 else{await writeFile(resolve(root,path),content);console.log('Built '+path+' ('+Buffer.byteLength(content)+' bytes)')}
}
