import { catalog, generateTrace } from '../src/trace-engine.js';
const $=id=>document.getElementById(id);
const ui={options:$('algorithmGrid'),bars:$('bars'),name:$('algorithmTitle'),category:$('algorithmCategory'),desc:$('algorithmDesc'),code:$('pseudocode'),status:$('statusBadge'),operation:$('activity'),progress:$('progressFill'),progressText:$('progressText'),stepStat:$('stepStat'),compStat:$('compStat'),swapStat:$('swapStat'),writeStat:$('writeStat'),passStat:$('passStat'),sizeStat:$('sizeStat'),play:$('playBtn'),pause:$('pauseBtn'),step:$('stepBtn'),back:$('backBtn'),reset:$('resetBtn'),shuffle:$('shuffleBtn'),sizeRange:$('sizeRange'),sizeOutput:$('sizeOutput'),speedRange:$('speedRange'),speedOutput:$('speedOutput'),preset:$('preset'),custom:$('customInput'),apply:$('applyBtn'),message:$('inputMessage'),theme:$('themeBtn'),best:$('bestComplexity'),avg:$('averageComplexity'),worst:$('worstComplexity'),space:$('spaceComplexity'),stable:$('stability'),hint:$('stepHint')};
let algorithm='bubble',initial=[],frames=[],cursor=0,running=false,timer=null,theme='light';
const random=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
function makeData(n,type){const a=Array.from({length:n},()=>random(5,95));if(type==='reverse'||type==='nearly'||type==='sorted')a.sort((a,b)=>a-b);if(type==='reverse')a.reverse();if(type==='nearly'&&n>=3){let i=random(0,n-2),j=random(i+1,n-1);[a[i],a[j]]=[a[j],a[i]]}return a}
function stop(){running=false;clearTimeout(timer);timer=null}
function rebuild(values){stop();initial=[...values];frames=generateTrace(initial,algorithm);cursor=0;ui.sizeRange.value=String(Math.max(2,Math.min(48,values.length)));ui.sizeOutput.textContent=values.length;render()}
function speed(){return Math.round(900/Math.pow(1.85,Number(ui.speedRange.value)-1))}
function animate(){if(!running)return;if(cursor>=frames.length-1){stop();render();return}cursor++;render();if(running)timer=setTimeout(animate,speed())}
function play(){if(running)return;if(cursor>=frames.length-1)cursor=0;running=true;animate()}
function pause(){stop();render()}
function step(){stop();cursor=Math.min(cursor+1,frames.length-1);render()}
function back(){stop();cursor=Math.max(0,cursor-1);render()}
function reset(){stop();cursor=0;render()}
function selectAlgorithm(key){if(!Object.hasOwn(catalog,key))return;algorithm=key;rebuild(initial);drawAlgorithms();drawDetails()}
function drawAlgorithms(){ui.options.innerHTML=Object.entries(catalog).map(([key,v],i)=>'<button class="algorithm '+(key===algorithm?'selected':'')+'" data-algo="'+key+'" aria-pressed="'+(key===algorithm)+'"><span class="alg-num">'+String(i+1).padStart(2,'0')+'</span><span class="alg-name">'+v.name+'</span><small>'+v.abbr+'</small></button>').join('')}
function drawDetails(){let data=catalog[algorithm];ui.name.textContent=data.name+' / '+data.english;ui.category.textContent=data.family;ui.desc.textContent=data.summary;ui.best.textContent=data.best;ui.avg.textContent=data.avg;ui.worst.textContent=data.worst;ui.space.textContent=data.space;ui.stable.textContent=data.stable?'稳定 STABLE':'不稳定 UNSTABLE';ui.stable.className=data.stable?'stable':'unstable';ui.code.innerHTML=data.code.map((line,i)=>'<div class="code-line"><span>'+String(i+1).padStart(2,'0')+'</span><code></code></div>').join('');Array.from(ui.code.children).forEach((row,i)=>row.querySelector('code').textContent=data.code[i])}
function render(){const f=frames[cursor];if(!f)return;const n=f.values.length;const min=n?Math.min(...f.values):0,max=n?Math.max(...f.values):0,spread=Math.max(1,max-min);const frag=document.createDocumentFragment();
 f.values.forEach((v,i)=>{const bar=document.createElement('div');bar.className='bar';if(f.kind==='complete'||f.sorted.includes(i))bar.classList.add('sorted');else if(f.active.includes(i))bar.classList.add(f.kind==='swap'?'swapping':f.kind==='write'?'writing':f.kind==='count'||f.kind==='bucket'?'collecting':'comparing');bar.style.height=(14+((v-min)/spread)*73)+'%';bar.title='下标 '+i+'：'+v;bar.setAttribute('aria-label','第 '+(i+1)+' 个元素 '+v);if(n<=24){const label=document.createElement('span');label.className='bar-value';label.textContent=String(v);bar.append(label)}frag.append(bar)});
 ui.bars.replaceChildren(frag);ui.bars.setAttribute('aria-label','当前数组：'+f.values.join(', '));ui.compStat.textContent=f.comparisons;ui.swapStat.textContent=f.swaps;ui.writeStat.textContent=f.writes;ui.passStat.textContent=f.pass;ui.stepStat.textContent=cursor+'/'+(frames.length-1);ui.sizeStat.textContent=n;ui.operation.textContent=f.detail;ui.progress.style.width=(frames.length<=1?100:cursor/(frames.length-1)*100).toFixed(1)+'%';ui.progressText.textContent=Math.round(cursor/Math.max(1,frames.length-1)*100)+'%';const done=cursor===frames.length-1;ui.status.textContent=done?'✓ 排序完成':running?'● 正在运行':cursor?'Ⅱ 已暂停':'○ 准备就绪';ui.status.className='status'+(done?' complete':running?' playing':cursor?' paused':'');ui.play.textContent=done?'↻ 再播放':'▶ '+(cursor?'继续播放':'开始排序');ui.pause.disabled=!running;ui.step.disabled=done;ui.back.disabled=cursor===0;ui.hint.textContent='共 '+Math.max(0,frames.length-1)+' 帧 · '+(f.kind==='compare'?'比较':f.kind==='swap'?'交换':f.kind==='write'?'写入':f.kind==='pass'?'轮次变化':f.kind==='count'?'频次统计':f.kind==='bucket'?'分桶':f.kind==='complete'?'完成':'就绪');const lines=Array.from(ui.code.children);lines.forEach(l=>l.classList.remove('active'));const targets={bubble:{compare:3,swap:4},selection:{compare:3,swap:5},insertion:{compare:3,write:4},shell:{compare:4,write:5},merge:{compare:4,write:5},quick:{compare:4,swap:5},heap:{compare:4,swap:5},counting:{count:1,write:4},radix:{write:3,pass:2},bucket:{bucket:2,compare:4,write:5}};const line=targets[algorithm]?.[f.kind];if(Number.isInteger(line)&&lines[line])lines[line].classList.add('active')}
function error(msg){ui.message.textContent=msg;ui.message.classList.add('error')}
function applyCustom(){const raw=ui.custom.value.trim(),tokens=raw.split(/[\s,，、;；]+/).filter(Boolean);if(tokens.length<2||tokens.length>48||!tokens.every(s=>/^[-+]?\d+$/.test(s))){error('请输入 2–48 个整数，使用逗号或空格分隔。');return}const values=tokens.map(Number);if(!values.every(Number.isSafeInteger)||values.some(v=>Math.abs(v)>999)){error('每个整数必须在 -999～999 范围内。');return}rebuild(values);ui.message.classList.remove('error');ui.message.textContent='✓ 已载入 '+values.length+' 个整数：'+values.join(', ');ui.custom.value=''}
function applyTheme(next){theme=next;document.documentElement.setAttribute('data-theme',theme);ui.theme.textContent=theme==='light'?'☾ 深色模式':'☀ 亮色模式';ui.theme.setAttribute('aria-label','切换到'+(theme==='light'?'深色':'亮色')+'模式');try{localStorage.setItem('sorting-lab-theme',theme)}catch{}}
ui.options.addEventListener('click',e=>{const btn=e.target.closest('[data-algo]');if(btn)selectAlgorithm(btn.dataset.algo)});
ui.play.addEventListener('click',play);ui.pause.addEventListener('click',pause);ui.step.addEventListener('click',step);ui.back.addEventListener('click',back);ui.reset.addEventListener('click',reset);ui.shuffle.addEventListener('click',()=>{rebuild(makeData(Number(ui.sizeRange.value),ui.preset.value));ui.message.classList.remove('error');ui.message.textContent='✓ 已根据选定的数据分布生成新数组'});
ui.sizeRange.addEventListener('input',()=>rebuild(makeData(Number(ui.sizeRange.value),ui.preset.value)));
ui.speedRange.addEventListener('input',()=>{ui.speedOutput.textContent=ui.speedRange.value+'×'});
ui.preset.addEventListener('change',()=>rebuild(makeData(Number(ui.sizeRange.value),ui.preset.value)));
ui.apply.addEventListener('click',applyCustom);
ui.custom.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();applyCustom()}});
ui.theme.addEventListener('click',()=>applyTheme(theme==='light'?'dark':'light'));
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||['INPUT','BUTTON','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.code==='Space'){e.preventDefault();running?pause():play()}else if(e.code==='ArrowRight'){e.preventDefault();step()}else if(e.code==='ArrowLeft'){e.preventDefault();back()}});
try{theme=localStorage.getItem('sorting-lab-theme')==='dark'?'dark':'light'}catch{}
applyTheme(theme);drawAlgorithms();drawDetails();rebuild(makeData(22,'random'));
